from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
driver = webdriver.Chrome()
from selenium.webdriver.common.keys import Keys
driver.get("https://www.flipkart.com/")
sleep(3)
driver.maximize_window()
login_close=driver.find_element(By.CLASS_NAME,"b3wTlE")
login_close.click()
sleep(3)
search=driver.find_element(By.NAME,"q")
search.send_keys("Bluetooth Speakers")
search.send_keys(Keys.ENTER)
sleep(3)
brand= driver.find_element(By.XPATH,"//div[text()='Brand']")
brand.click()
sleep(5)
brand=driver.find_element(By.XPATH,"//div[text()='boAt']")
brand.click()
sleep(2)
rating=driver.find_element(By.XPATH,"//div[text()='4★ & above']")
sleep(5)
rating.click()
sleep(5)
price=driver.find_element(By.XPATH,"//div[text()='Price -- Low to High']")
price.click()
sleep(5)
first=driver.find_element(By.XPATH,"//img[@class='UCc1lI']")
first.click()
sleep(5)
driver.switch_to.window(driver.window_handles[1])
sleep(5)
gr=driver.find_elements(By.XPATH,"//div[contains(text(),'Flipkart')]")
print(len(gr))
sleep(5)
add_cart=driver.find_element(By.XPATH,"//div[text()='Add to cart']")
add_cart.click()
sleep(5)
cart=driver.find_element(By.XPATH,"//img[@alt='Cart']")
cart.click()
sleep(5)
driver.save_screenshot("cart_result.png")

